[package]
name = "catalyst_window"
version = "0.1.0"
edition = "2024"

[dependencies]
flecs_ecs = { workspace = true }
catalyst_core = { workspace = true }
winit = { workspace = true }
log = { workspace = true }